baseURL = "https://ezbotTNT.github.io/"
title = "ezbot TNT"
theme = "dot"

# customize color
[params]
primaryColor = "#00008C"
secondaryColor = "#EBF5FF"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"
enable=false

[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  languageCode = "en-us"
  title = "EzBot-BitMex        TNT"
  dateFormat = "23 October 2019"
  home = "Home"
  # logo is for all page
  logo = ""
  # logo white is for homepage logo, you can use colorful logo too...
  logoWhite = ""
  copyright = "The ezbio24.com site are Cooperate © [ezbot24](https://ezbot24.com/) 2019."

    # navigation
    [Languages.en.menu]

         [[Languages.en.menu.main]]
          name = "소개페이지"
          url = "1_intro"
          weight = 10

         [[Languages.en.menu.main]]
          name = "설치하기"
          url = "2_how_to_install"
          weight = 11

          [[Languages.en.menu.main]]
          name = "용어 및 기능설정"
          url = "3_document"
          weight = 11

          [[Languages.en.menu.main]]
          name = "설치파일 다운로드"
          url = "4_install_file"
          weight = 12

        [[Languages.en.menu.main]]
          name = "FaQ"
          url = "faq"
          weight = 15


    # banner
    [Languages.en.params.banner]
      title = "Support Center & Knowledge base"
      description = "Find advice and answers from our support team fast or get in touch"
      image = "images/banner.jpg"
      placeholder = "Have a question? Just ask here or enter terms"

    # Topics
    [Languages.en.params.topics]
      title = "설치하시기 전에 알아야 하는 정보입니다."

 
    # contact
    [Languages.en.params.contact]
      title = "Got Any Questions"
      content = "Submit the form and confirm your email address at <a class='text-primary' href='https://formspree.io/'>Formspree</a> Then add the following lines to contact page YAML Front Matter."

    # footer social icon
    [[Languages.en.socialIcon]]
      icon = "ti-facebook"
      linkURL = "#"

    [[Languages.en.socialIcon]]
      icon = "ti-twitter-alt"
      linkURL = "#"

    [[Languages.en.socialIcon]]
      icon = "ti-vimeo-alt"
      linkURL = "#"

    [[Languages.en.socialIcon]]
      icon = "ti-instagram"
      linkURL = "#"



