baseURL = "https://ezbotTNT.github.io/"
languageCode = "en-us"
title = "New Dragon Hak"
theme = "learn"

[author]
    name = "yonghakshin"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  editURL = "https://github.com/ezbotTNT/ezbotTNT.github.io/edit/master/content/"
  description = "hugo content for ezbotTNT.github.io"
  author = "yonghakshin"